name: Daily Checkin

on:
  schedule:
    - cron: '0 16 * * *'  # 每天凌晨0点运行（UTC时间）
  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # 使用适合的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL: ${{ vars.EMAIL }}
          PASSWD: ${{ vars.PASSWD }}
          SCKEY: ${{ secrets.SCKEY }}
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python main.py  # 替换为实际的脚本文件名
